# Site settings
title: Great New Blog Title
author:
  name: Evan Will
  email: your-email@domain.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
# Build settings
remote_theme: pages-themes/architect@v0.2.0
